Implementation for a Network-Wide Stop Command
TimoCloud/TimoCloud-5 pull request #31
Opened 2018-08-22 18:40 UTC by Zorro909

This pull Request implements the StopCommand with a Protocol Addition of the Message Type "SHUTDOWN" which tells the Server to shutdown immediately.
In addition the Servers now won't shutdown due to a loss of connection to the core and instead will try to reconnect afterwards. Since a hard exit is now not needed to stop the system, the servers won't die just because the Core died.

2018-08-22 21:35 UTC, TimoCrafter commented
What about the Core‘s current state? The Core requires the list of running servers/proxies in order to work properly

2018-08-22 21:49 UTC, TimoCrafter commented
What is this PR‘s goal? Should it avoid accidental stopping of the core or make updating easier?

2018-08-23 16:24 UTC, Zorro909 commented
This PR should make shutting down the whole Network easier, since shutting down the Core leaves the other parts running. On the other hand if a error occurs in the Core and it crashes or sth. similar happens, all MC Servers and such would shut down immediately, which disrupts the Player Experience. And about the currently running servers and proxies, they reconnect immediately after the Core started again, so it should be able to recognize that they are online or did i miss something on that part?

PS: I'm working together with a Server Team that requested this feature to be in a CloudSystem that they would want to use. And i thought it could also help others, so if you have any suggestions as to how it could be handled better, i'm completely open for that.

2018-08-23 17:02 UTC, TimoCrafter commented
Have you tested it? Servers/proxies won‘t be able to reconnect properly, since they aren‘t registered in the CoreInstanceManager and their token will be rejected when they want to do the handshake.

I think it‘s impossible for the Core to crash. Even if it did, the whole network wouldn‘t work anymore (synchronisation). Stopping the whole network can also be done simpler: Just leave the system as it currently is, and add a shutdown command to stop bases and cords.

2018-08-23 20:32 UTC, Zorro909 commented
What exactly was the point behind the token-based session system?

2018-08-26 10:31 UTC, Zorro909 commented
Since i don't think this leads to anywhere, i'm gonna use this project as a base and develop it further as a fork. 
Thanks

2018-08-26 10:44 UTC, TimoCrafter commented
Sorry, since I was on vacation, I didn‘t see your question about the token authentication system. It‘s all about security - in order to prevent foreign servers to connect and control your network via the API.

Please don‘t give up - I appreciate your pull request! Though, I think a lot about features before implementing them. Hence, I would enjoy discussing your PR with you and implement the resulting solution instead of leading you to go your own way.

2018-08-26 11:06 UTC, Zorro909 commented
Oh, okay, then how about we meet on the discord server and try to figure everything out? The Owner of the Server i am working with and I have a lot of features/things in mind that we would like to optimize, so i would really appreciate if we could work together on that.

2020-10-03 09:09 UTC, niklasnikki approved these changes
Everything is okay

2020-10-03 12:14 UTC, TimoZikeli requested changes

2020-10-03 12:14 UTC, TimoZikeli commented on TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/bukkit/sockets/BukkitStringHandler.java
> +            	if(TimoCloudBukkit.getInstance().getServerName().equalsIgnoreCase((String) message.get("name"))) {
Shouldn‘t the server just get shutodwn messages which are addressed to it?

2020-10-03 12:14 UTC, TimoZikeli commented on TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/bungeecord/TimoCloudBungee.java
> +	private static TimoCloudBungee instance;
Please use the TimoCloud default indentation.

2020-10-03 12:14 UTC, TimoZikeli commented on TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/bungeecord/sockets/BungeeStringHandler.java
> +            	if(TimoCloudBungee.getInstance().getProxyName().equalsIgnoreCase((String) message.get("name"))) {
Shouldn‘t the proxy just get shutdown messages which are addressed to it?

2020-10-03 12:14 UTC, TimoZikeli commented on TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/core/objects/Proxy.java
> +    	getBase().sendMessage(Message.create().setType("SHUTDOWN").set("name", getName()));
Why are you sending the message to the base?

2020-10-03 12:17 UTC, TimoZikeli commented
Apart from the requested changes, some of the used methods are already outdated by now :)
In addition, I strongly believe that this PR has not been tested because it is impossible that the servers reconnect after the Core has been restarted because the Core's state is not being saved.

Hence, I am closing it for now.

2020-10-03 12:17 UTC, closed without merging