Add a message to the Lobby command
TimoCloud/TimoCloud-5 pull request #8
Opened 2018-03-05 17:30 UTC by Lasergott

2018-03-05 17:32 UTC, TimoZikeli requested changes

2018-03-05 17:32 UTC, TimoCrafter commented on TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/bungeecord/commands/LobbyCommand.java
> +            BungeeMessageManager.sendMessage(sender,TimoCloudBungee.getInstance().getFileManager().getConfig().getString("LobbyCommandMessage"));
One-line if syntax does not work with two lines - use brackets

2018-03-05 17:32 UTC, TimoCrafter commented on TimoCloud-Universal/src/main/resources/bungeecord/config.yml
> +LobbyCommandMessage: 'Successful connected to a Lobby server'
We do not want messages in `config.yml` - create an extra messages file

2018-03-05 17:37 UTC, TimoCrafter commented on TimoCloud-Universal/src/main/resources/bungeecord/config.yml
> +LobbyCommandMessage: 'Successful connected to a Lobby server'
Please use proper english - "Successfully" ;)

2018-03-05 17:38 UTC, TimoCrafter commented on TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/bungeecord/commands/LobbyCommand.java
> +            BungeeMessageManager.sendMessage(sender,TimoCloudBungee.getInstance().getFileManager().getConfig().getString("LobbyCommandMessage"));
We also want messages if there is no free server or if the player already is on the only free Lobby.

2018-03-05 18:43 UTC, TimoZikeli requested changes

2018-03-05 18:43 UTC, TimoCrafter commented on TimoCloud-Universal/src/main/resources/bungeecord/messages.yml
> +LobbyConnect: '&aSuccessfully connected to a Lobby server'
‚&aSuccessfully connected to &6{server_name}‘

2018-03-05 18:43 UTC, TimoCrafter commented on TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/bungeecord/commands/LobbyCommand.java
> +        BungeeMessageManager.sendMessage(sender, TimoCloudBungee.getInstance().getFileManager().getConfig().getString("LobbyConnect"));
.replace(„{server_name}“, serverInfo.getName());

2018-03-05 18:53 UTC, Lasergott commented
It is okay now? xD

2018-03-06 17:55 UTC, TimoZikeli approved these changes

2018-03-06 17:55 UTC, merged